export const MONSTER = {
  IMAGES: {
    MMR1_MOVE: 'mmr1-move',
    MMR1_IDLE: 'mmr1-idle',
    MMR2_MOVE: 'mmr2-move',
    MMR2_IDLE: 'mmr2-idle',
    LZR_MOVE: 'lzr-move',
    LZR_IDLE: 'lzr-idle',
    JBG_MOVE: 'jbg-move',
    JBG_IDLE: 'jbg-idle',
    V87_MOVE: 'v87-move',
    V87_IDLE: 'v87-idle',
    YLG_MOVE: 'ylg-move',
    YLG_IDLE: 'ylg-idle',
    
  },
  ANIMATIONS: {
    MMR1_MOVE_LEFT: 'mmr1-move-left',
    MMR1_MOVE_RIGHT: 'mmr1-move-right',
    MMR1_MOVE_UP: 'mmr1-move-up',
    MMR1_MOVE_DOWN: 'mmr1-move-down',
    MMR1_IDLE_DOWN: 'mmr1-idle-down',
    MMR2_MOVE_LEFT: 'mmr2-move-left',
    MMR2_MOVE_RIGHT: 'mmr2-move-right',
    MMR2_MOVE_UP: 'mmr2-move-up',
    MMR2_MOVE_DOWN: 'mmr2-move-down',
    MMR2_IDLE_DOWN: 'mmr2-idle-down',
    LZR_MOVE_LEFT: 'lzr-move-left',
    LZR_MOVE_RIGHT: 'lzr-move-right',
    LZR_MOVE_UP: 'lzr-move-up',
    LZR_MOVE_DOWN: 'lzr-move-down',
    LZR_IDLE_DOWN: 'lzr-idle-down',
    JBG_MOVE_LEFT: 'jbg-move-left',
    JBG_MOVE_RIGHT: 'jbg-move-right',
    JBG_MOVE_UP: 'jbg-move-up',
    JBG_MOVE_DOWN: 'jbg-move-down',
    JBG_IDLE_DOWN: 'jbg-idle-down',
    V87_MOVE_LEFT: 'v87-move-left',
    V87_MOVE_RIGHT: 'v87-move-right',
    V87_MOVE_UP: 'v87-move-up',
    V87_MOVE_DOWN: 'v87-move-down',
    V87_IDLE_DOWN: 'v87-idle-down',
    YLG_MOVE_LEFT: 'ylg-move-left',
    YLG_MOVE_RIGHT: 'ylg-move-rYLG',
    YLG_MOVE_UP: 'ylg-move-up',
    YLG_MOVE_DOWN: 'ylg-move-down',
    YLG_IDLE_DOWN: 'ylg-idle-down',

    MONSTER_DEATH: 'monster-death',
  },
} as const;

// template
// ${T}_MOVE: '${t}-move',
// ${T}_IDLE: '${t}-idle',
// ${T}_MOVE_LEFT: '${t}-move-left',
// ${T}_MOVE_RIGHT: '${t}-move-right',
// ${T}_MOVE_UP: '${t}-move-up',
// ${T}_MOVE_DOWN: '${t}-move-down',
// ${T}_IDLE_DOWN: '${t}-idle-down',

